In [1]:
import pandas as pd

C:\Users\Kasim\AppData\Local\Temp\ipykernel_19152\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
job_df = pd.read_csv("job_descriptions.csv")
print("Job Descriptions Dataset Preview:")
job_df.head()

Job Descriptions Dataset Preview:

         Job_Title                                    Job_Description
0        ICU Nurse  Minimum 2 years experience, BLS certification ...
1  Pediatric Nurse  Experience with emergency response, ACLS prefe...
2   Surgical Nurse  Comfortable with geriatric care, excellent bed...
3         ER Nurse  Familiar with advanced monitoring equipment, I...
4  Geriatric Nurse  Ability to work night shifts, experience with ...

In [3]:
print("\nJob Descriptions Dataset Info:")
job_df.info()

Job Descriptions Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Job_Title        10 non-null     object
 1   Job_Description  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [4]:
print("\nJob Descriptions Dataset Statistics:")
job_df.describe(include='all')

Job Descriptions Dataset Statistics:

        Job_Title                                    Job_Description
count          10                                                 10
unique         10                                                 10
top     ICU Nurse  Minimum 2 years experience, BLS certification ...
freq            1                                                  1

In [5]:
print("\nMissing Values in Job Descriptions Dataset:")
job_df.isnull().sum()

Missing Values in Job Descriptions Dataset:

Job_Title          0
Job_Description    0
dtype: int64

In [6]:
nurse_df = pd.read_csv("nurse_profiles.csv")
print("\nNurse Profiles Dataset Preview:")
nurse_df.head()

Nurse Profiles Dataset Preview:

,Name,Specialty,Years_Experience,Certifications,Patient_Satisfaction_Score,Successful_Recoveries,Shift_Type,Employment_Type
0,Kevin Green,ICU Nurse,27,"BLS, ACLS",3.94,548,Rotational,Contract
1,Emma Wilson,Home Health Nurse,26,"BLS, PALS, ENPC",4.90,743,Day,Contract
2,Charlie Lewis,Psychiatric Nurse,4,"BLS, ACLS, TNCC",4.47,609,Night,Part-time
3,Liam Adams,ER Nurse,19,"BLS, ACLS, TNCC",4.14,609,Night,Full-time
4,Mia Adams,Oncology Nurse,15,BLS,3.35,329,Night,Full-time

In [7]:
print("\nNurse Profiles Dataset Info:")
nurse_df.info()

Nurse Profiles Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Name                        100 non-null    object
 1   Specialty                   100 non-null    object
 2   Years_Experience            100 non-null    int64
 3   Certifications              100 non-null    object
 4   Patient_Satisfaction_Score  100 non-null    float64
 5   Successful_Recoveries       100 non-null    int64
 6   Shift_Type                  100 non-null    object
 7   Employment_Type             100 non-null    object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.4+ KB

In [9]:
print("\nNurse Profiles Dataset Statistics:")
nurse_df.describe(include='all')

Nurse Profiles Dataset Statistics:

,Name,Specialty,Years_Experience,Certifications,Patient_Satisfaction_Score,Successful_Recoveries,Shift_Type,Employment_Type
count,100,100,100.00000,100,100.000000,100.000000,100,100
unique,88,10,NaN,10,NaN,NaN,3,3
top,Samuel James,ICU Nurse,NaN,"BLS, PALS, ENPC",NaN,NaN,Rotational,Contract
freq,3,17,NaN,20,NaN,NaN,39,36
mean,NaN,NaN,14.31000,NaN,4.036200,527.610000,NaN,NaN
std,NaN,NaN,8.76828,NaN,0.600737,280.197293,NaN,NaN
min,NaN,NaN,1.00000,NaN,3.020000,65.000000,NaN,NaN
25%,NaN,NaN,7.00000,NaN,3.562500,287.500000,NaN,NaN
50%,NaN,NaN,12.50000,NaN,4.075000,541.000000,NaN,NaN
75%,NaN,NaN,23.00000,NaN,4.522500,749.500000,NaN,NaN
max,NaN,NaN,30.00000,NaN,4.990000,997.000000,NaN,NaN

In [10]:
print("\nMissing Values in Nurse Profiles Dataset:")
nurse_df.isnull().sum()

Missing Values in Nurse Profiles Dataset:

Name                          0
Specialty                     0
Years_Experience              0
Certifications                0
Patient_Satisfaction_Score    0
Successful_Recoveries         0
Shift_Type                    0
Employment_Type               0
dtype: int64

In [11]:
job_df.duplicated().sum()

0

In [12]:
nurse_df.duplicated().sum()

0